### ISSUE TITLE
[Linux-SGX] Hardening in/out OCALL params

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/graphene#1236]
I am doing deep security analysis of OCALL in/out arguments (+ return values). **WIP!**

-  `ocall_create_process`:
    - [x] Return value must be checked for `== 0` or `==<set of allowed errors>`. Currently if attacker returns a positive value, then `pid` and `procfds[]` are not updated but the caller `_DkProcessCreate()` thinks that they were updated and may proceed with garbage in these values. Also, strange error codes seem to be benign (`_DkProcessCreate()` fails on any negative return value), but it's better to sanitize them.
    - [x] Pass `args[]` to child as part of encrypted checkpoint. UPDATE: Done in https://github.com/oscarlab/graphene/pull/1609.
    - [x] Check that returned `pid` and `procfds[]` are indeed new FDs and not currently open FDs (otherwise attacker can e.g. force parent process to overwrite an open file). UPDATE: This sounds like a useless verification.

-  `ocall_clone_thread`:
    - [x] Return value must be checked for `== 0` or `==<set of allowed errors>`. The current implementation looks benign, but it's better to sanitize error codes.

-  `ocall_resume_thread`:
    - [x] Return value must be checked for `== 0` or `==<set of allowed errors>`. The current implementation looks benign, but it's better to sanitize error codes.

- `ocall_sleep`:
    - [x] `microsec` must be sanity-checked: at least that it is less than original `microsec` (this shows remaining time due to interrupt).
    - [x] Return value must be checked for `== 0` or `==<set of allowed errors>`. The current implementation looks benign, but it's better to sanitize error codes.

- `ocall_exit`:
    - [x] noreturn; hangs app if attacker unexpectedly returns (this countermeasure is already implemented)

- `ocall_mmap_untrusted`:
    - [ ] *low priority*: Check that returned untrusted-memory region does not overlap with already-existing untrusted-memory regions. (We can ignore it, and then Graphene's FS/TLS shields will detect such a violation via integrity checks.)
    - [x] Return value must be checked for `== 0` or `==<set of allowed errors>`. The current implementation looks benign, but it's better to sanitize error codes.

- `ocall_munmap_untrusted`:
    - [ ] *low priority*: Check that untrusted-memory region is one of the already-existing untrusted-memory regions.
    - [x] Return value must be checked for `== 0` or `==<set of allowed errors>`. The current implementation looks benign, but it's better to sanitize error codes.

- `ocall_futex`:
    - [x] Return value must be checked for `== 0` or `==<set of allowed errors>`. The current implementation looks benign, but it's better to sanitize error codes.

- `ocall_gettime`:
    - [x] Check that returned clock value is monotonically increasing. This requires saving the previous value and synchronizing parallel OCALLs. UPDATE: Done in https://github.com/oscarlab/graphene/pull/2554.
    - [x] Return value must be checked for `== 0` or `==<set of allowed errors>`. The current implementation looks benign, but it's better to sanitize error codes.

**Misc:**
- `_DkVirtualMemoryFree`:
    - [x] Why does it call `ocall_munmap_untrusted()`? Is there really a case when this is needed? Try to remove this case!

- All DkMutex and DkEvent code at LibOS level:
    - [x] LibOS must implement additional synchronization guards (e.g., in-enclave variables to double-check that DkEvent/DkMutex synchronization at untrusted-PAL level didn't return prematurely). UPDATE: Done when Borys re-wrote DkEvent and got rid of DkMutex, see https://github.com/oscarlab/graphene/pull/2336 and https://github.com/oscarlab/graphene/pull/2361.

**Comment by dimakuv** [comment]
This needs to be done. Quite important.

**Comment by boryspoplawski** [comment]
#2554 does `ocall_gettime`

**Comment by dimakuv** [comment]
This issue was finally fixed by #2621. I forgot to link this issue to that PR, so closing it now manually.
