### ISSUE TITLE
[LibOS] epoll on pipes reports EPOLLOUT on read end of pipe

### ISSUE THREAD

**Issue by boryspoplawski** [gramineproject/graphene#1717]
## Description of the problem
When doing `epoll_wait` on read end of pipe with `EPOLLIN | EPOLLOUT` set, both of those are reported after successful wait.
This faulty behavior is due to the fact, that in Graphene pipes are emulated with (unix) sockets, which are bidirectional by nature.

## Steps to reproduce
See test at https://github.com/boryspoplawski/graphene/commit/98d49f08bf66900eb419335cc7b1cf094f90b649

**Comment by dimakuv** [comment]
That's a bit strange. I thought we had this logic of eliminating "impossible" events for different types of handles. In this case, I was expecting our emulation of `epoll_wait()` to check "ok, it's a read end of the pipe, I should remove EPOLLOUT from its `events`".

**Comment by boryspoplawski** [comment]
That would be a sane way of handling this, but I can't find such logic anywhere in the source.
Btw, this is quite a edge case and no sane app will try doing this.

**Comment by dimakuv** [comment]
@boryspoplawski Is this still relevant?

**Comment by boryspoplawski** [comment]
Afaik yes.
