### ISSUE TITLE
Forwarding selected host environment variables

### ISSUE THREAD

**Issue by boryspoplawski** [gramineproject/graphene#1840]
## Description of the feature

It would be nice to be able to forward some environment variables from the untrusted host e.g. by specifying their names in the manifest.
Example use case: providing the application with a ip+port/domain to connect to (which by definition can be manipulated by the untrusted host anyway).

Please note that this is a different feature than `loader.insecure__use_host_env`, which is intended only for testing purposes and this one is also suitable for production usages, as it allows fine-grained control of what's passed to the app.

**Comment by jtakeshi-nd** [comment]
This feature would be useful for my current work, to be able to disable threads when running a binary in SGX without having to recompile dependencies using OpenMP. It's possible to disable threading programmatically in my program source, but it would be nice to specify at runtime.

**Comment by mkow** [comment]
This was implemented in https://github.com/gramineproject/gramine/pull/56.
