### ISSUE TITLE
Document how to build without networking

### ISSUE THREAD

**Issue by thiagomacieira** [gramineproject/graphene#1846]
## Description of the problem
Package building runs in an environment without network access. So Graphene must document a way of building without hitting the network. Any dependencies that any normal build would download need to be listed, with instructions on where to place the files.

## Steps to reproduce
Type `make`

## Expected results
Build works.

## Actual results
Build fails because downloads failed.
```
make[3]: Entering directory '/builddir/build/BUILD/graphene-eb39597b5f3b93d99858ed6b4332b35801d9a6e6/Pal/lib'
../../Scripts/download --output ../include/lib/uthash.h --url https://raw.githubusercontent.com/troydhanson/uthash/8b214aefcb81df86a7e5e0d4fa20e59a6c18bc02/src/uthash.h --sha256 ba9af0e8c902108cc40be8e742ff4fcbb0e93062d91aefd6070b70d4e067c2ac
../../Scripts/download --output crypto/mbedtls-2.21.0.tar.gz --url https://github.com/ARMmbed/mbedtls/archive//mbedtls-2.21.0.tar.gz --sha256 320e930b7596ade650ae4fc9ba94b510d05e3a7d63520e121d8fdc7a21602db9
download: Trying to fetch https://raw.githubusercontent.com/troydhanson/uthash/8b214aefcb81df86a7e5e0d4fa20e59a6c18bc02/src/uthash.h
--2020-09-25 10:59:20--  https://raw.githubusercontent.com/troydhanson/uthash/8b214aefcb81df86a7e5e0d4fa20e59a6c18bc02/src/uthash.h
Connecting to 127.0.0.1:9... failed: Connection refused.
download: WARNING: Hash mismatch: Expected ba9af0e8c902108cc40be8e742ff4fcbb0e93062d91aefd6070b70d4e067c2ac but received e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
download: ERROR: Failed to download '../include/lib/uthash.h' (ba9af0e8...)! No URLs left to try.
```

**Comment by mkow** [comment]
+1

It's worth noting that offline builds are supported (via `DL_OFFLINE` + `DL_CACHE` parameters, see `Scripts/download`) but this isn't documented anywhere.

**Comment by cathhuo** [comment]
+1. --2021-05-11 07:13:39--  (try: 3)  https://raw.githubusercontent.com/troydhanson/uthash/8b214aefcb81df86a7e5e0d4fa20e59a6c18bc02/src/uthash.h
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... failed: Connection refused.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|::|:443... failed: Cannot assign requested address.
