### ISSUE TITLE
[LibOS] file/dir attributes of chroot are incorrect after created and removed multiply times

### ISSUE THREAD

**Issue by llly** [gramineproject/graphene#2104]
## Description of the problem
`struct shim_file_data` contains  member `bool queried;` to mark that file attributes are up to date. There is one place to set it to true in chroot while no place to set it to false.
https://github.com/oscarlab/graphene/blob/e395e0133ed121640160a5f63a04d104ea3a59ed/LibOS/shim/src/fs/chroot/fs.c#L257
https://github.com/oscarlab/graphene/blob/e395e0133ed121640160a5f63a04d104ea3a59ed/LibOS/shim/src/fs/chroot/fs.c#L305
`struct shim_file_data` are reused when access same file/directory name. Error occurred if the file/directory is a different one. For example remove it and create another with same name.

## Steps to reproduce
Very simple C code
```
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <unistd.h>

#define TESTDIR "testdir"

int main(int argc, char** argv) {
    int ret = 0;

    if ((ret = rmdir(TESTDIR)) < 0 && errno != ENOENT) {
        perror("rmdir");
        exit(1);
    }

    if ((ret = mkdir(TESTDIR, 0700)) < 0) {
        perror("mkdir");
        exit(1);
    }
    if ((ret = rmdir(TESTDIR)) < 0) {
        perror("rmdir");
        exit(1);
    }
    if ((ret = mkdir(TESTDIR, 0700)) < 0) {
        perror("mkdir");
        exit(1);
    }

    int fd2 = open(TESTDIR "/file", O_RDWR | O_CREAT | O_EXCL, 0600);

    if (fd2 < 0) {
        perror("open without O_CREAT");
        return 1;
    }
    close(fd2);
    unlink(TESTDIR "/file");
    if ((ret = rmdir(TESTDIR)) < 0) {
        perror("rmdir");
        exit(1);
    }



    return 0;
}
```
## Expected results
No error

## Actual results
Failed to create file in dir because dir attributes are incorrect.
log
```
[P17566:T1:dir] ---- shim_rmdir("testdir") = -2
[P17566:T1:dir] ---- shim_mkdir("testdir", 448) = 0x0
[P17566:T1:dir] ---- shim_rmdir("testdir") = 0x0
[P17566:T1:dir] ---- shim_mkdir("testdir", 448) = 0x0
[P17566:T1:dir] ---- shim_openat(AT_FDCWD, "testdir/file", O_RDWR|O_CREAT|O_EXCL, 0600) = -13
[P17566:T1:dir] ---- shim_dup(2) = 0x3
[P17566:T1:dir] ---- shim_fcntl(3, F_GETFL, 0x74a71a0f4222) = 0x401
[P17566:T1:dir] ---- shim_close(3) = 0x0
[P17566:T1:dir] ---- shim_write(2, 0x74a71a79f2a0, 0x28) ...
open without O_CREAT: Permission denied
```
I also debugged it using earlier commit because I cannot step in to LibOS using latest trunk. Here is the wrong  `struct shim_file_data` in `shim_openat`.
```
305         if (!data->queried && (ret = __query_attr(dent, data, pal_handle)) < 0) {
(gdb) p *data
$2 = {lock = {lock = 0x7f3328082890 <g_mem_pool+19408>, owner = 1}, version = {counter = 1}, queried = true, type = FILE_DIR, mode = 0, size = {counter = 0}, host_uri = {hash = 0, len = 13,
    name = "dir:./testdir", '\000' <repeats 18 times>, oflow = 0x0}, atime = 0, mtime = 0, ctime = 0, nlink = 2}
```

**Comment by dimakuv** [comment]
The FS component of Graphene must be re-written completely. Unfortunately, it's just way too messy and buggy. It doesn't make sense to fix these bugs one by one.

> I also debugged it using earlier commit because I cannot step in to LibOS using latest trunk. 

Really? I just tried it out (on commit e395e0133ed121640160a5f63a04d104ea3a59ed), I see no issues.

**Comment by llly** [comment]
@dimakuv After I clean and rebuild again, debugger can work indeed.
