### ISSUE TITLE
sendmmsg fails to send multiple messages on a socket returns error EINVAL

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/graphene#2291]
## Description of the problem
sendmmsg - It is used to send multiple message on a socket.
sendmmsg01 tests fails in do_sendmsg while doing DkStreamWrite which  write to stream at absolute offset. The function returns 4 as a unix error which is 22 in linux(EINVAL)

## Expected results
/root/Graphene_Master/LibOS/shim/test/ltp/src/lib/tst_buffers.c:55: TINFO: Test is using guarded buffers
/root/Graphene_Master/LibOS/shim/test/ltp/src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 05m 00s
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:113: TINFO: Testing variant: vDSO or syscall with libc spec
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:74: TPASS: First message received successfully
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:79: TPASS: Second message received successfully
/root/Graphene_Master/LibOS/shim/test/ltp/src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 05m 00s
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:113: TINFO: Testing variant: syscall with old kernel spec
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:74: TPASS: First message received successfully
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:79: TPASS: Second message received successfully

Summary:
passed   4
failed   0
skipped  0
warnings 0

## Actual results
/root/Graphene_Master/LibOS/shim/test/ltp/src/lib/tst_buffers.c:55: TINFO: Test is using guarded buffers
/root/Graphene_Master/LibOS/shim/test/ltp/src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 05m 00s
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:113: TINFO: Testing variant: vDSO or syscall with libc spec
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:48: TFAIL: sendmmsg() failed: EINVAL (22)
/root/Graphene_Master/LibOS/shim/test/ltp/src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 05m 00s
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:113: TINFO: Testing variant: syscall with old kernel spec
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:48: TFAIL: sendmmsg() failed: EINVAL (22)

Summary:
passed   0
failed   2
skipped  0
warnings 0

**Comment by anjalirx-intel** [comment]
Retested with release 1.2rc1 and issue is still reproducible
