### ISSUE TITLE
[Examples] `python-simple` HTTP web-server test fails with `localhost` on Glibc 2.33 + Python 3.8

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/graphene#2335]
## Description of the problem

This issue was detected while working on https://github.com/oscarlab/graphene/pull/2325. Currently in that PR, I worked around this issue, but we need to figure out the root cause.

In our `python-simple` example, we have a simple web-server and a simple web-client Python scripts:
- https://github.com/oscarlab/graphene/blob/master/Examples/python-simple/scripts/dummy-web-server.py
- https://github.com/oscarlab/graphene/blob/master/Examples/python-simple/scripts/test-http.py

The latter uses the `urllib` package. The error I observed happens inside this package.

For some reason, the `urllib3` package used in Python 3.8 (which is the default on Ubuntu 20.04) and backed by Glibc 2.33 tries to perform:
1. `socket(AF_INET6)` 
2. `bind(<sock>, ::1:0)` (notice the zero port)
3. `connect(<sock>)`

This sequence actually results in `EADDRNOTAVAIL` error when Graphene tries to perform host-level `bind()`. The Graphene log looks something like this (I added some additional log messages):
```
[P25729:T1:python3.8] trace: ---- shim_socket(INET6, SOCK_CLOEXEC|STREAM, 0) = 0x3
error: [tcp_listen 0] uri = [0000:0000:0:0000:0000:0000:0000:0001]:0
error: [tcp_listen 4] this is AF_INET6 socket
error: [tcp_listen 4] bind returned -99 (bind_addr=0x7f52f5c86950, bind_addrlen=28)
[P25729:T1:python3.8] error: bind: invalid handle returned
[P25729:T1:python3.8] trace: ---- shim_bind(3, 0x7b75343e99b0, 28) = -13
[P25729:T1:python3.8] trace: ---- shim_close(3) = 0x0
```

This doesn't happen on Python 3.6 (default on Ubuntu 18.04). This also doesn't happen on Glibc 2.31. So the only combination where I observed this error is: **Python 3.6 + Glibc 2.33 + Ubuntu 20.04**.

I did some research but didn't get to anything meaningful.
- The offending Python line is: https://github.com/oscarlab/graphene/blob/658de0e002ac782e2effc9334db359a4e09c879a/Examples/python-simple/scripts/test-http.py#L4. It looks like the `urllib3` package tries to find a default network interface to bind to (which is already weird -- the client typically does `socket() + connect()`, but this package wants to do `socket() + bind() + connect()`).
- The `shim_bind()` that fails in the log is most probably this line: https://github.com/python/cpython/blob/10ee2662dfeeb3b00d232f8f1c2eecc4d7e65244/Lib/socket.py#L795.
- `getaddrinfo()` in this package is also suspicious: https://github.com/python/cpython/blob/10ee2662dfeeb3b00d232f8f1c2eecc4d7e65244/Lib/socket.py#L787. That's where we get the IPv6 (`AF_INET6`) loopback address.

We should create some simple tests to test IPv6 extensively and to test the `socket + bind + connect` logic on the client. It is very hard to debug Python...

**Comment by dimakuv** [comment]
This seems to be a specific case of our general issue of "Fix all problems with our sockets". We need to refactor that code, and test more with IPv6 and UNIX sockets. For now, closing this.

**Comment by mkow** [comment]
Wouldn't this be worth keeping open then? Sounds useful for testing the changes in the networking code.
