### ISSUE TITLE
`getsockname` on AF_UNIX sockets causes a crash

### ISSUE THREAD

**Issue by srcman** [gramineproject/graphene#2393]
## Description of the problem

Using `getsockname()` or `getpeername()` on UNIX domain sockets crashes Graphene.

## Steps to reproduce

Create a UNIX domain socket with, e.g., `socket()` or `socketpair()`, and call `getsockname()` or `getpeername()` on the socket.

(A particular situation where this problem occurs is if a UNIX socket object is printed in Python, but this bug is not Python-specific in any way and is reproducible also with C code.)

Tested with Graphene 75962a8 (current master branch).

## Expected results

The expected result is that the functions would work also with UNIX domain sockets, ideally perhaps with similar results as Linux produces for different types of UNIX sockets.

## Actual results

`debug: DkProcessExit: Returning exit code 1` is printed and Graphene exits.

Currently it seems that regardless of the socket type, both `shim_do_getsockname()` and `shim_do_getpeername()` call `inet_copy_addr()`, which seems intended only for AF_INET/AF_INET6 addresses and aborts if given (e.g.) an AF_UNIX socket.

**Comment by dimakuv** [comment]
Thanks for reporting this bug!

> Currently it seems that regardless of the socket type, both shim_do_getsockname() and shim_do_getpeername() call inet_copy_addr(), which seems intended only for AF_INET/AF_INET6 addresses and aborts if given (e.g.) an AF_UNIX socket.

Yes, I'm pretty sure your analysis is correct. Hopefully we'll find some time soon to fix this bug.

**Comment by jkr0103** [comment]
Please assign to me

**Comment by jkr0103** [comment]
@srcman Could you share the sample you are trying to execute with graphene?
