### ISSUE TITLE
[Pal/Linux-SGX] Handle leak in `pipe_connect`

### ISSUE THREAD

**Issue by mkow** [gramineproject/graphene#2467]
## Description of the problem

There seem to be a thread handle leak in `pipe_connect()` function in Linux-SGX PAL:
https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/Pal/src/host/Linux-SGX/db_pipes.c#L244

`thread_hdl` is never closed anywhere.

There doesn't seem to be any easy fix for this, we can't just close the handle while the thread is still running.

**Comment by dimakuv** [comment]
This is tied to the fact that we generally don't have a way to close/free PAL-thread handles. See also https://github.com/oscarlab/graphene/issues/1030#issuecomment-879950108.

So we need to solve a general problem of "how to safely close and free a PAL thread handle". The memory leaks are very small though, so assigning a low priority.
