### ISSUE TITLE
Graphene is creating file with wrong permissions and also reading it incorrectly

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/graphene#2543]
## Description of the problem
TestCase is trying to create a file with 0777 permissions, the file created has 0755 permissions and Graphene is reporting the file permissions as 700

TC: umask(2) sets the mask from 0000 to 0777 while we create files, the previous value of the mask should be returned correctly, and the file mode should be correct for each creation mask

## Steps to reproduce
Run LTP test umask01
Only 1 test has been executed for reference. File path has been updated for reference. Detailed log has been attached
File path:  /tmp/testfile

## Expected results
TPASS: All files created with correct mode

Summary:
passed   0
failed   0
skipped  0
warnings 0

## Actual results
**graphene-direct ./umask01**
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
/root/Graphene_Master/LibOS/shim/test/ltp/ltp_src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 05m 00s
/root/Graphene_Master/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/umask/umask01.c:51: TFAIL: File mode got 700, expected 777

Summary:
passed   0
failed   1
skipped  0
warnings 0

```
root@ubuntu-test-base:$ ls -alrt /tmp/
total 60
-rwxr-xr-x  1 root root     0 Jul 13 04:31 testfile

```

## Label
P0, bug

[umask01_graphene.log](https://github.com/oscarlab/graphene/files/6814045/umask01_graphene.log)

**Comment by mkow** [comment]
File permissions are not supported in Graphene and I don't think we need them for any real-world workload.

**Comment by dimakuv** [comment]
The actual issue is that Graphene created the file with some default permissions, but it reported back absolutely different permissions (there is no internal consistency). It looks like the permissions-to-return are hard-coded to some arbitrary value. This is bad.

**Comment by dimakuv** [comment]
Looks like the file mode creation mask (`umask`) is initially zero, before the first call to `umask()`: https://github.com/oscarlab/graphene/blob/af2f7809b36945382a535f95c2af7a2b32a2059a/LibOS/shim/src/bookkeep/shim_process.c#L46

I didn't debug where file permissions come from (other than they come from `dent->perm`), but it looks like LibOS permissions are correctly set to whatever user requests, but they are not propagated to PAL and to the host FS. Which is probably fine? We need Pawel to explain the status of all this...

**Comment by sahason** [comment]
Regarding the issue, graphene creating the file with some default permissions (0755), but it reported back different permissions (0700) I have submitted a PR gramineproject/gramine#10

As per my understanding regarding the issue file having default permission (0755) always even though umask is used to set file mode creation mask, the current implementation of `shim_do_umask` does not set the file creation mask in the host by inline syscall. As the default umask in Linux is 0022 the file permissions are always 0755. As file permission is not supported in graphene hope the PR gramineproject/gramine#10 is enough to close this issue.

**Comment by pwmarcz** [comment]
* The chroot filesystem rewrite (https://github.com/gramineproject/gramine/pull/5) should cause Gramine to report back the same permissions as it applied, because the permissions are now cached and not read from host.
* We will still report *previously unknown* files incorrectly (e.g. already existing on host, or created by another process), gramineproject/gramine#10 should fix that.
* Gramine doesn't really support umask: it initializes umask to 0, not 0022, as Linux does; and completely ignores it when creating a new file. Let me go and fix that...
