### ISSUE TITLE
Proper implementation of eventfd

### ISSUE THREAD

**Issue by bigdata-memory** [gramineproject/graphene#2552]
## Description of the problem
As we know, we have to enable the following option in manifest to use evenfd related syscall. 
`sys.insecure__allow_eventfd = 1`
The reason is that the internal counter value maintained by kernel outside of SGX enclave. some applications relies on event fd for complex networking operations. e.g. ipykernel.

**Comment by mkow** [comment]
This isn't a security vulnerability in Graphene as the title indicates, the option is explicitly marked as insecure.
If I understand correctly, you just request a new feature to be implemented? (an in-LibOS emulation of eventfd)

**Comment by bigdata-memory** [comment]
Yes, we need a secure eventfd that should be emulated in LibOS as the counter value may get leaked internal states if the kernel got compromised, thanks.

**Comment by boryspoplawski** [comment]
> some applications relies on event fd for complex networking operations.
But we will never have a secure event fd which wait's for notifications from untrusted host (which is what you want, right?)

Also, what's the point of running networking software in SGX?

**Comment by bigdata-memory** [comment]
It could be the case of IPC among multiple GSGX enclaves via wrapped counter by secrets provisioned through attestation.

**Comment by boryspoplawski** [comment]
I'm not sure if I understood you correctly, but:
- eventfd shared between processes - yes, we can implement this with IPC, but that would only allow for **in** Graphene processes to use it,
- eventfd shared between Graphene and host OS - this we cannot do with any meaningful security/correctness guarantees.

I suppose it's the 2nd case you are interested in?

**Comment by bigdata-memory** [comment]
`eventfd shared between processes - yes, we can implement this with IPC, but that would only allow for in Graphene processes to use it`
This case is what we expected, e.g. A frontend (Browser UI) service <-> its backends, all of them are running inside of GSGX enclaves for higher level of security.
`eventfd shared between Graphene and host OS - this we cannot do with any meaningful security/correctness guarantees.`
This one would also be useful when user doesn't want to run the frontend service in SGX enclave for some reasons.

**Comment by dimakuv** [comment]
So there are two sub-problems in this issue:
1. Implementing secure eventfd shared between Graphene processes: possible but requires a lot of implementation effort.
2. Implementing secure eventfd shared between Graphene and host OS: not possible.

For the sub-problem 1, we can assign a rather low priority. It is a nice feature to have, but will take long to implement it.

**Comment by mkow** [comment]
To be honest, I still don't see any legitimate use for this. How do you want to run a browser in an enclave and what's the point of doing so? It's a GUI app...

**Comment by mkow** [comment]
Closing, as I don't see any reasonable usecase for this feature.
