### ISSUE TITLE
Unable to Sign the graphenized Docker image using gsc sign-image:

### ISSUE THREAD

**Issue by ntk97** [gramineproject/graphene#2684]
## Unable to Sign the graphenized Docker image using gsc sign-image:
I am trying build GSC for avalon-python-worker, I have avalon-python-worker docker image. signing of graphenized image is failed. 

## Steps to reproduce

- `git clone https://github.com/hyperledger/avalon.git`
- `cd avalon/tc/graphene/python_worker/`
- `docker-compose `build` builds the docker image  avalon-python-worker-dev 
- `git clone https://github.com/gramineproject/graphene.git`
- After building graphene by following the doc https://graphene.readthedocs.io/en/latest/quickstart.html#quick-start-with-sgx-support
- `cd Tools/gsc`
- `cp config.yaml.template config.yaml`
- `openssl genrsa -3 -out enclave-key.pem 3072`
- `./gsc build --insecure-args avaolon-python-worker-dev test/ubuntu18.04-python3.manifest`
- `./gsc sign-image avalon-python-worker-dev enclave-key.pem`

### The step `./gsc sign-image python enclave-key.pem` fails saying 
**Parsing /entrypoint.manifest as TOML failed: Found invalid character in key name: '.'. Try quoting the key name.**

Using Graphene master branch

Actually I have used existing python manifest file.

URLS followed :
- https://github.com/hyperledger/avalon/tree/main/tc/graphene/python_worker
- https://graphene.readthedocs.io/en/latest/manpages/gsc.html

**Comment by dimakuv** [comment]
First of all, I don't know about this Avalon Docker image (`avalon-python-worker-dev`). I can see that the relevant page in the Avalon repo (https://github.com/hyperledger/avalon/tree/main/tc/graphene/python_worker) was last updated 7 months ago, so it may be incompatible with Graphene and GSC.

However, your steps do not seem to have any particular assumptions about Avalon and its integration with Graphene. You seem to use that Avalon Docker image as a normal input image for GSC. GSC technically should just work with any Docker image.

The error message about the "invalid character in key name" is surprising. We need to look into this deeper.

Can you peek into the `gsc-avalon-python-worker-dev-unsigned` Docker container using a bash session and examine the `entrypoint.manifest` file? If possible, you can attach this file to this GitHub issue, and maybe we can look and identify the problem. (Or you can try to do it yourself, by finding the offending TOML key.)

**Comment by sahason** [comment]
@dimakuv Please assign this to me.

**Comment by dimakuv** [comment]
This was actually fixed by https://github.com/gramineproject/gsc/pull/10 which we just merged. I'm closing but @ntk97 please test on your side that it works now.

**Comment by ntk97** [comment]
I tested with the PR [GSC] Install toml python package properly gramineproject/gsc#15, it worked

**Comment by dimakuv** [comment]
@ntk97 Yes, but now you can test with the `master` branch of GSC. I mean, you won't need to use that PR; you can just use the master now.
