### ISSUE TITLE
Adjust timeout on retries within shim_do_epoll_wait()

### ISSUE THREAD

**Issue by thomasknauth** [gramineproject/graphene#435]
https://github.com/oscarlab/graphene/blob/0488ac6961c56dd5f299f8952914c8b2bd2d1845/LibOS/shim/src/sys/shim_epoll.c#L347

If the epoll fd is modified while waiting for events, shim_do_epoll_wait() re-issues the system call to reflect the changes. However, before re-issuing, the timeout should be adjusted, to reflect the time already spent waiting.

**Comment by donporter** [comment]
Good point.  Thanks for the fix

**Comment by dimakuv** [comment]
This is still a valid issue. We didn't fix this stuff, see https://github.com/oscarlab/graphene/blob/8d239ea6efeb071d0b733d80e0247408dce8e441/LibOS/shim/src/sys/shim_epoll.c#L351. This is low priority though.

**Comment by dimakuv** [comment]
Still valid issue: https://github.com/oscarlab/graphene/blob/4cb98219d8e302055587a8952c1102415a72ba42/LibOS/shim/src/sys/shim_epoll.c#L373

We haven't encountered any real-world problems with this though, so this is very low priority.
