### ISSUE TITLE
[Pal/Linux-SGX] Rename `enclave_tls` to `pal_tcb_sgx`

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/graphene#638]
* TLS stands for "Thread Local Storage" and is a memory area dedicated to storing app-specific thread-local variables.

* TCB stands for "Thread Control Block" and contains thread-specific internal state such as thread ID, stack pointer, and saved registers.

The Linux PAL correctly defines the struct `pal_tcb`. The Linux-SGX PAL however defines the struct `enclave_tls`. The `enclave_tls` name is misleading and breaks uniformity of code (see e.g. #555).

I suggest to rename:
* `struct enclave_tls` to `struct pal_tcb_sgx`
* `SET/GET_ENCLAVE_TLS` to `SET/GET_ENCLAVE_TCB`
* `sgx_tls.h` to `sgx_tcb.h`

If agreed, this change should be enacted after #555  is merged.

**Comment by yamahata** [comment]
+1 for naming consistency.

**Comment by mkow** [comment]
+1, though I also don't like "TCB", as it's used in SGX nomenclature as "Trusted Code Base". But we probably won't find any better name.

**Comment by HW42** [comment]
I also always read "trusted code base" first. But the suggested change seems reasonable.

**Comment by HW42** [comment]
SGX calls it internal thread specific state TCS ("Thread Control Structure"). So something like GTCS (Graphene TCS, to avoid confusion with the SGX's TCS) would be an options. But this naming might be too SGX specific.

**Comment by dimakuv** [comment]
@HW42: TCS is too SGX-specific. I still prefer TCB.
