### ISSUE TITLE
socket options initialized to random values in Linux-SGX PAL

### ISSUE THREAD

**Issue by smherwig** [gramineproject/graphene#674]
In the Linux-SGX PAL, a socket's options are initialized to random values.  Specifically, `tcp_connect`, `tcp_listen`, and `tcp_accept`, `udp_bind`, and `udp_connect` in `Pal/src/host/Linux-SGX/db_sockets.c` call `socket_create_handle` with an uninitialized stack variable, `sock_options`.  In each of these cases, the corresponding ocall would have set this value via `sgx_enclave.c's` `sock_getopt`, but this function is currently a placeholder and does not do anything.  `socket_create_handle` then copies the `sock_options` into the corresponding `hdl->sock` information.  When an application later calls `setsockopt`, the handle may therefore show that this option is already set, and the `__do_setsockopt` function in 
`LibOS/shim/src/sys/shim_socket` thus skip the call to `DkStreamAttributesSetByHandle`.

The actual problem I experienced was that my application, outside of SGX, has dramatic performance improvements when Nagle's algorithm is disabled (that is, sets the `TCP_NODELAY`).  However, in the enclave, there was no difference whether this option was set or not, and performance was bad.

The solution is just to `memset(&sock_options, 0x00, sizeof(struct sockopt))` after each stack allocation of that variable in `db_sockets.c`

**Comment by dimakuv** [comment]
Thanks for the bug report!

Indeed, `sock_options` is not initialized. In fact, the corresponding PR should have two bugfixes:
1. `memset(&sock_options, 0, sizeof(sock_options))` after each stack allocation for sanity.
2. Adequate implementation of `sgx_enclave.c: sock_getopt()` -- need to understand the internal structure of `Linux-SGX/linux_types.h: struct sockopt` and how to map it to Linux's `struct sockopt` (note that -- annoyingly -- these two are very different).

Do you have a toy test case for this? Have you tried under normal Linux PAL, does it work correctly there?

**Comment by martinschmatz** [comment]
Question: Should actually all fields in the struct sockopt be initialized to zero when the stack allocation is done?

In particular, SO_REUSEADDR is never set (empty operation in __do_setsockopt in shim_socket.c), but reported always as '1' by shim_do_getsockopt - which leads to the question of whether or not this flag should actually always be initialized to '1'.

**Comment by dimakuv** [comment]
You are probably right. If this is indeed the case, then this particular flag should be initialized with 1. I didn't have the time to get to this bugfix.

**Comment by martinschmatz** [comment]
I actually started to try it out, initialized all available sockopts to zero and then one more try with REUSADDR = 1. 
But in both cases, my application didn't fprint any more and refused to open a file. 
Hence I changed back to original - and still no fprint, no file opening. Need to understand this first and then will try again.
While writing: Could the recent changes (e.g get/setrlimits) cause the no fprint, no file open issue?

**Comment by dimakuv** [comment]
I don't see how recent changes could cause this issue. Are you sure there is nothing suspicious in the output log (when you have `debug = inline` in manifest)? Maybe the recent changes uncovered a previously hidden bug in your app/graphene. Also, at this point it is easier to GDB.

**Comment by martinschmatz** [comment]
I have the suspicion that I'm having some bug in my manifest file - because now I get the following error (right in the beginning, during enclave initialization, before even any inline debugging messages show up; I can successfully run examples): 

*** An unexpected AEX vector occurred inside PAL. Exiting the thread. ***
(vector = 0x2, type = 0x0 valid = 0, RIP = +0x000073bd)
rax: 0xe001a0b64325c rcx: 0x6fece62e rdx: 0x00000000 rbx: 0x80bfa97d0
rsp: 0x80ffe89e8 rbp: 0x80ffe8a20 rsi: 0x80bfa9808 rdi: 0x80bfa97d0
r8 : 0x6fffffff r9 : 0x70000021 r10: 0x00000031 r11: 0x6ffffdff
r12: 0x00000001 r13: 0x37ffff1a0 r14: 0x6ffffeff r15: 0x37ffffa00
rflags: 0x00010202 rip: 0x80bd7c3bd

Sorry that this slows me down experimenting with the initialization of the sockopts....

**Comment by dimakuv** [comment]
Hm, vector=2 is NMI exception... You can try to do `objdump -D <your-app>` and see what is the instruction at address `RIP = +0x000073bd`. Maybe this will give you a hint. And I know people hate it, but `GDB=1` is the first thing to use in these situations.

**Comment by martinschmatz** [comment]
FYI - I had to debug my build configs (OpenSSL, cURL, etc) quite a bit to make sure that my library dependencies are all built using GLIBC2.19 despite my server running Ubuntu 18.04LTS. 
I now - finally - have a build config which works again. 
I can now (re-)start to look into the issue that sock_options is not initialized. Once done, I'll post my results and insights here....

**Comment by martinschmatz** [comment]
I added the relevant initialization to zero (and SO_REUSEADDR to 1) after each stack allocation of the struct sockopt variable in db_sockets.c in a test environment. 
I didn't see any problems and will issue a PR in the next couple of days.

**Comment by dimakuv** [comment]
Thanks. Happy to review and merge your PR asap.

**Comment by dimakuv** [comment]
>Indeed, sock_options is not initialized. In fact, the corresponding PR should have two bugfixes:
> 1. memset(&sock_options, 0, sizeof(sock_options)) after each stack allocation for sanity.
> 2. Adequate implementation of sgx_enclave.c: sock_getopt() -- need to understand the internal structure of Linux-SGX/linux_types.h: struct sockopt and how to map it to Linux's struct sockopt (note that -- annoyingly -- these two are very different).

We still didn't fix item 2. So keeping this issue open.

**Comment by dimakuv** [comment]
Item 2 is still not fixed on current master: https://github.com/oscarlab/graphene/blob/4cb98219d8e302055587a8952c1102415a72ba42/Pal/src/host/Linux-SGX/sgx_enclave.c#L334

Though it's not very important, so Priority 2.
