### ISSUE TITLE
ppoll and pselect6 ignore sigmask

### ISSUE THREAD

**Issue by donporter** [gramineproject/graphene#789]
Our implementations of these system calls ignore sigmask and sigsetsize.

**Comment by donporter** [comment]
Same with epoll_pwait

**Comment by dimakuv** [comment]
Still valid on current master: https://github.com/oscarlab/graphene/blob/af2f7809b36945382a535f95c2af7a2b32a2059a/LibOS/shim/src/sys/shim_epoll.c#L465-L466

Given that we have complete and correct signal handling in LibOS (courtesy of Borys), this could actually be easily implemented. But we haven't encountered applications that rely on this, so priority is low.
